#!/bin/bash 
#### Description: Protege as branches informadas no repositório remoto - GitLab
#### Requirements: 
####   - curl
#### Written by: 
####   - Tiago Costa - tiago.costa@mv.com.br on 10-2015
####   - Julio Tobias - julio.tobias@mv.com.br on 10-2015

set -o errexit
set -o pipefail
#set -o nounset
#set -o xtrace

#Checkagem se os 2 parâmetros obrigatórios estão definidos
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then
	echo "Selecione as branches do projeto para realizar a o procedimento:"
	echo "ex:  protect-branches <GITLAB_ENDPOINT> <GITLAB_TOKEN> <GROUP_NAME/PROJECT_NAME> <DEFAULT_BRANCH>"
	echo ""
	exit 1
fi

# Something like https://yourhost/api/v3
ENDPOINT=$1/api/v3
TOKEN=$2
GROUP_NAME=$(echo $3 | cut -d'/' -f1)
PROJECT_NAME=$(echo $3 | cut -d'/' -f2)
DEFAULT_BRANCH=$4

echo "################################"
echo "#### Definindo branch principal"
echo "### GitLab:       ${1}"
echo "### Group Name:   ${GROUP_NAME}"
echo "### Project Name: ${PROJECT_NAME}"
echo "### Setting default branch: ${DEFAULT_BRANCH}"

export API="curl --fail -sk -H 'Content-Type:application/json' -X PUT $ENDPOINT"

eval ${API}/projects/${GROUP_NAME}%2F${PROJECT_NAME}?private_token=$TOKEN -d \'{ \"default_branch\":\"${DEFAULT_BRANCH}\"}\'

echo ""
echo "============================================="
echo "=    Branch default definida com Sucesso    ="
echo "============================================="

