#!/bin/bash 
#### Description: Realiza a importação do CVS para GIT, com as APIs "git cvsimport" e "cvs2git"
#### Written by: 
####   - Tiago Costa - tiago.costa@mv.com.br on 10-2015
####   - Julio Tobias - julio.tobias@mv.com.br on 10-2015

function cvs_info() {
	file="no_such_file"    #use non existing file
	result=$(cvs -tn status $file 2>&1)
	export CVS_URL=$(echo "$result" | grep -Pzo "open_connection_to_server \((.*?)\)" | cut -d'(' -f2 | cut -d')' -f1)
	if [[ -z "$CVS_URL" ]]; then
	       export CVS_URL=$(echo "$result" | grep -Pzo "CVSROOT=(.*)" | cut -d'=' -f2)
	fi


	export CVS_ROOT=$(echo $CVS_URL | cut -d':' -f4)
	export cvsuserhost=$(echo $CVS_URL | cut -d':' -f3)
	export cvsmodule_pattern="Reader_Lock\(${CVS_ROOT}"

	export CVS_MODULE=$(echo "$result" | grep -Pzo "${cvsmodule_pattern}(.*?)\)") 
	export CVS_MODULE=$([[ "$CVS_MODULE" =~ $cvsmodule_pattern(.*?)\) ]] && echo ${BASH_REMATCH[1]})
	export CVS_USER=$(echo $cvsuserhost | cut -d'@' -f1)
	export CVS_HOST=$(echo $cvsuserhost | cut -d'@' -f2)
}

function process_options() {
	set -o errexit
	set -o pipefail
	#set -o xtrace
	#set -o nounset

	#Set Script Name variable
	SCRIPT=`basename ${BASH_SOURCE[0]}`

	#Initialize variables to default values.
	OPT_T="BASE"
	OPT_Y=
	OPT_X=
	OPT_i=
	OPT_C=

	#Set fonts for Help.
	BOLD=`tput bold`
	NORM=`tput sgr0`

	#Help function
	function HELP {
		exit 1
	}

	### Start getopts code ###

	#Parse command line flags
	#If an option should be followed by an argument, it should be followed by a ":".
	#Notice there is no ":" after "h". The leading ":" suppresses error messages from
	#getopts. This is required to get my unrecognized option code to work.
	while getopts 123Ct:yx FLAG; do
		case $FLAG in
			1|2|3)
				OPT_i=$FLAG
			;;
			C)
				OPT_C=1
			;;
			t)  #set option "a"
				OPT_T=$OPTARG
			;;
			y)  #set option "y"
				OPT_Y=-y
			;;
			x)
				OPT_X=-x
				set -o xtrace
			;;
			h)  #show help
				HELP
			;;
			\?) #unrecognized option - show help
				echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
				HELP
				#If you just want to display a simple error message instead of the full
				#help, remove the 2 lines above and uncomment the 2 lines below.
				#echo -e "Use ${BOLD}$SCRIPT -h${NORM} to see the help documentation."\\n
				#exit 2
			;;
		esac
	done

	shift $((OPTIND-1))  #This tells getopts to move on to the next argument.
	### End getopts code ###
}

function gitImportMethod() {
	
	opt=$1

	if [ "$opt" = "Cvs2Git" ]; then
		$GITCVS_HOME/cvs2git-import -t $OPT_T $OPT_X $CVS_HOST $CVS_ROOT $CVS_MODULE $project_name $ignored_files 
	elif [ "$opt" = "CvsImport" ]; then
		$GITCVS_HOME/git-cvsimport $CVS_HOST $CVS_ROOT $CVS_MODULE $project_name $ignored_files $project_remote
	elif [ "$opt" = "Comparar" ]; then
		$GITCVS_HOME/compare-cvsimport $CVS_HOST $CVS_ROOT $CVS_MODULE $project_name $ignored_files $project_remote
	fi
}
